#!/usr/bin/env python
# -*- coding:utf-8 -*-
"""
给出两个由小写字母组成的字符串。

字符串由随机洗牌字符串产生，然后在一个随机位置添加一个字母。

找到在T中添加的字母。
ord map
Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s and then add one more letter at a random position.

Find the letter that was added in t.

Example:

Input:
s = "abcd"
t = "abcde"

Output:
e

Explanation:
'e' is the letter that was added.
"""
class Solution(object):
    def findTheDifference(self, s, t):
        """
        :type s: str
        :type t: str
        :rtype: str
        """
        return chr(sum(map(ord, t)) - sum(map(ord, s)))

obj = Solution()
print(obj.findTheDifference("abcd","abcde"))